title: Termission
description: Cross-platform Serial/TCP Terminal with Scriptable Auto-Responder
show_downloads: true
google_adsense: ca-pub-1135979461412092
google_analytics: G-MKQK789F6L
theme: jekyll-theme-cayman
